[Accessibility] Disabled radio-group should not be focusable #47
AlaskaAirlines/auro-radio pull request #109
Opened 2023-06-21 07:40 UTC by fajar-apri-alaska

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #47 

## Summary:
adding a condition inside resetRadio function handler when setting the tabIndex

## Type of change:

Please delete options that are not relevant.

- [x] Revision of an existing capability

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-06-28 00:56 UTC, blackfalcon requested changes

2023-06-28 00:56 UTC, blackfalcon commented on .npmrc
> +legacy-peer-deps=true
This would actually be a `build` or `ci` prefix. This update has no impact in a released version or the performance of the element to the consumer.

2023-06-29 17:10 UTC, blackfalcon commented
Please rebase off of the latest release. https://auro.alaskaair.com/contributing/upstream

2023-06-29 17:10 UTC, blackfalcon requested changes
Fork is out of date with the primary repo.

2023-07-03 03:22 UTC, fajar-apri-alaska commented
Hi @blackfalcon,
I have rebased off upstream master, please tell me if it is good.
Thanks~

2023-07-07 22:49 UTC, blackfalcon commented
Will be adding this code update to the following PR 

- https://github.com/AlaskaAirlines/auro-radio/pull/111

2023-07-10 03:44 UTC, fajar-apri-alaska commented
> Will be adding this code update to the following PR
> 
> * https://github.com/AlaskaAirlines/auro-radio/pull/111

OK, I will also put above PR in my watch list.

2023-07-20 08:37 UTC, fajar-apri-alaska commented
I am going to close this PR since changes already included in #111. Thanks~

2023-07-20 08:37 UTC, closed without merging