Update repo using new version of generator
AlaskaAirlines/auro-radio pull request #111
Opened 2023-06-30 18:34 UTC by jordanjones243

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #110 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

Update repo to support Node 18+ and other modernized standards using the new version of the `WC-Generator`.

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-07-07 21:35 UTC, blackfalcon requested changes
I added a commit that updates the main demo page. When I ran the api.html file, there are a lot of private properties and methods being exposed. These need to be updated in the code. 

Also, the api.html page is not fully flushed out. Most of the links do not go anywhere.

2023-07-07 22:47 UTC, blackfalcon commented
Please also see this update https://github.com/AlaskaAirlines/auro-radio/pull/109/files and add to this PR.

2023-07-10 21:22 UTC, jordanjones243 commented on docs/partials/demo.md
> +  <!-- AURO-GENERATED-CONTENT:START (FILE:src=./../../apiExamples/customRadio.html) -->
The custom version of auro-radio is not behaving correctly, circle back around to this to figure out the issue

2023-07-18 05:14 UTC, jason-capsule42 requested changes
New file requested by Dale `.npmrc` in an earlier comment was not addressed.

The the `demoPublish` workflow needs to be added.

2023-07-18 18:28 UTC, jordanjones243 commented
> New file requested by Dale `.npmrc` in an earlier comment was not addressed.
> 
> The the `demoPublish` workflow needs to be added.

`.npmrc` has already been added in a previous commit, `publishDemo.yml` now added.

2023-07-19 17:06 UTC, jason-capsule42 approved these changes

2023-07-19 17:17 UTC, merged

2023-07-19 19:48 UTC, blackfalcon commented
:tada: This PR is included in version 1.7.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-radio/v/1.7.0)
- [GitHub release](https://github.com/AlaskaAirlines/auro-radio/releases/tag/v1.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: