575975 add onChange attribute to radio button
AlaskaAirlines/auro-radio pull request #12
Opened 2020-11-17 23:15 UTC by ychae-alaska

# Alaska Airlines Pull Request

**Fixes:** #11 

## Summary:
In a scenario where there are multiple radio buttons within a radio group, and the selection of a radio button is supposed to display different content or have a custom event, I would expect to have a `change` event listener that supports bubbling. 

The scope of this work is to add the custom `change` event listener within the scope of the component to support this external event management.

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2020-11-17 23:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AlaskaAirlines/auro-radio?pullRequest=12) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AlaskaAirlines/auro-radio?pullRequest=12) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AlaskaAirlines/auro-radio?pullRequest=12) it.</sub>

2020-11-19 00:18 UTC, geoffrich requested changes
Just a couple comments. Once you make the changes, please squash your commits into a single commit that follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) (see previous commits in the repo for examples).

2020-11-19 00:18 UTC, geoffrich commented on demo/index.html
> +      <p>Group with onchange</p>
I don't we need to add anything to the demo for this. Input and change events are already being logged in the console for every radio button on the demo page.

2020-11-19 00:18 UTC, geoffrich commented on src/auro-radio.js
> +  handleChange(event) {
Can you update the "should fire a input event with correct data" test to also check for the change event?

2020-11-20 21:22 UTC, blackfalcon commented
It appears that the updates were made in the Github editing tools. The preference is to fork the repo, update, and run/test locally. Version control is based on [conventional commits](https://github.com/AlaskaAirlines/auro/blob/master/src/CONTRIBUTING.md#conventional-commits). This is part of the Auro Design System Contributing Guidelines.

2020-11-20 21:42 UTC, ychae-alaska commented
> It appears that the updates were made in the Github editing tools. The preference is to fork the repo, update, and run/test locally. Version control is based on [conventional commits](https://github.com/AlaskaAirlines/auro/blob/master/src/CONTRIBUTING.md#conventional-commits). This is part of the Auro Design System Contributing Guidelines.

Hm, I saw the forking guidelines in the "Contributions" section of the README and followed that. I'm not sure what you're seeing to think that it's edited from the browser.

2020-11-24 20:42 UTC, blackfalcon commented
@ychae-alaska you closed this PR? Is this update no longer needed? 

> Hm, I saw the forking guidelines in the "Contributions" section of the README and followed that. I'm not sure what you're seeing to think that it's edited from the browser.

The issue I see is that the comments are not formatted correctly. All the Auro repos use [conventional commits](https://github.com/AlaskaAirlines/auro-radio/blob/master/.github/CONTRIBUTING.md#conventional-commits). Why I think that you used the Github editor is because there are pre-commit hooks that should have not allowed you to push a branch without the correct commit format. 

The update request was valid and we appreciated your PR. If needed, we can assist with cleaning up the minor issues with the PR and get this merged.

2020-11-24 22:46 UTC, geoffrich requested changes
Small code style request -- `changeEventDetected` sounds like it should be a boolean. Holding the event type is redundant.

Otherwise looks great!

2020-11-24 22:46 UTC, geoffrich commented on test/auro-radio.test.js
> +      changeEventDetected = event.type;
```suggestion
      changeEventDetected = true;
```

2020-11-24 22:46 UTC, geoffrich commented on test/auro-radio.test.js
> +    expect(changeEventDetected).to.equal("change");
```suggestion
    expect(changeEventDetected).to.be.true;
```

2020-11-25 00:20 UTC, ychae-alaska commented
@blackfalcon - I'm not too familiar with GitHub and the conventions we may follow, so I'm sorry about that! I must have done some funky things as well as accidentally closing the PR. I'd really appreciate your help in cleaning up the PR.

2020-11-25 21:46 UTC, geoffrich approved these changes

2020-11-26 03:02 UTC, blackfalcon approved these changes

2020-11-26 03:03 UTC, merged

2020-11-26 03:05 UTC, ecommerceUXdesign commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alaskaairux/auro-radio/v/1.2.0)
- [GitHub release](https://github.com/AlaskaAirlines/auro-radio/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: