Implement optionSelected attribute
AlaskaAirlines/auro-radio pull request #128
Opened 2024-03-27 17:10 UTC by jordanjones243

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Resolves:** #97 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

* Implement `optionSelected` attribute to `auro-radio-group`
* Refactor doc examples

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2024-04-04 18:04 UTC, jason-capsule42 requested changes

2024-04-04 18:04 UTC, jason-capsule42 commented on apiExamples/basicGroup.html
> +  <auro-radio id="radio6" label="Maybe" name="radioDemo" value="maybe">Please send me more information</auro-radio>
Why did all the examples content change? It doesn't seem connected to the change for `optionSelected`.

2024-05-08 19:56 UTC, jordanjones243 commented
PR will be addressed once the form validation PR has been merged into the RC branch:
- https://github.com/AlaskaAirlines/auro-radio/pull/129

2024-05-09 18:07 UTC, jordanjones243 commented on test/auro-radio.test.js
> +  });
Currently, editing the `value` attribute does not affect the state of anything in the radio group, so I am not exactly sure what you are aiming to test. If you feel that you are on the track of something important, we can talk about it further. Keep in mind that this work will be released alongside the form validation work.

`value` attribute setting can be addressed in this ticket:
- https://github.com/AlaskaAirlines/auro-radio/issues/130

2024-05-09 18:12 UTC, jordanjones243 commented on docs/partials/api.md
> +The `error` attribute used to set an error state on a single `<auro-radio>` element.
The example is removed in the form validation repo.

2024-05-10 18:17 UTC, jason-capsule42 commented on test/auro-radio.test.js
> +  });
Resolving based on the future work ticket

2024-05-10 18:23 UTC, jason-capsule42 approved these changes

2024-05-10 18:23 UTC, merged