auro-radio: update label to use slot
AlaskaAirlines/auro-radio pull request #46
Opened 2021-07-03 20:25 UTC by blackfalcon

# Alaska Airlines Pull Request

**Fixes:** #40 

## Summary:

The scope of this update is to extend the placement of label content to use a pre-defined slot as well as add a new `content` slot that allows for greater creative content use within the scope of auro-radio. 

This is **NOT** a breaking change in the shape of the element. Users will still be allowed to add content via the `label` attribute, but using the slot will override the string from the attribute as shown in the following screenshot.

The display of the markup in the `content` slot is **NOT** managed by the auro-radio custom element. This markup is in the `light DOM` and able to be styled by the consumer.  

![Screen Shot 2021-07-03 at 1 11 07 PM](https://user-images.githubusercontent.com/181089/124366038-791db480-dc01-11eb-9fc8-e50b3f2b7f61.png)

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2021-07-07 18:10 UTC, jason-capsule42 requested changes

2021-07-07 18:10 UTC, jason-capsule42 commented on demo/index.html
> +                <b>Lounge $300 USD</b><br>
The break here isn't necessary (I tested the rendering with it removed) for the content to appear below the label. Including it lead me to initially think it was required to have the content slot not appear inline with the label.

```suggestion
                <b>Lounge $300 USD</b>
```

2021-07-12 16:35 UTC, jason-capsule42 requested changes
The line break on line 77 of the index.html (see comment in changes) should be removed.

2021-07-12 18:56 UTC, Dayna-A commented
Hey @blackfalcon tabbing through the demo page seems to jump from the top option in one auro-radio group to the middle option in the next to a different one in the one after that? Is this a side effect of the way the demo page is set up or something or is there cause for concern?

2021-07-12 19:06 UTC, Dayna-A commented
Is the tab focus supposed to jump to disabled radio groups? in the demo page in chrome on mac it seems to skip the individually disabled ones but not the disabled group for me.. screen recording: https://drive.google.com/file/d/13eODKqjOAX1c2_UctUdCPOZGFXkx-wjC/view

2021-07-12 20:50 UTC, Dayna-A submitted a review, later dismissed

2021-07-13 16:13 UTC, blackfalcon commented
@Dayna-A nope, that is a new bug. See https://github.com/AlaskaAirlines/auro-radio/issues/48

This new bug was NOT caused by this PR so I do not want to conflate this PR to address the bug.

2021-07-13 20:18 UTC, jason-capsule42 approved these changes

2021-07-13 21:36 UTC, merged

2021-07-13 21:39 UTC, AuroDesignSystem commented
:tada: This PR is included in version 1.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alaskaairux/auro-radio/v/1.5.0)
- [GitHub release](https://github.com/AlaskaAirlines/auro-radio/releases/tag/v1.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: