feat: add support for disabling individual auro-radio components within an auro-radio-group
AlaskaAirlines/auro-radio pull request #6
Opened 2020-10-14 21:54 UTC by tjgrist

# Alaska Airlines Pull Request

As a developer, I want to offer a radio group which allows for individual auro-radio components to be disabled without having to disable the entire auro radio-group.

## Summary:

Prior to this feature addition, the auro-radio-group only allowed for disabling the entire radio group. This PR adds support for having a radio group with one or more individual radio buttons disabled, as seen here: 
![image](https://user-images.githubusercontent.com/17755678/96049499-f5325b00-0e2c-11eb-843f-d6ea8ad99747.png)

## Type of change:

- [x] New capability

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2020-10-14 21:57 UTC, tjgrist commented
@blackfalcon These prs still don't seem to auto-assign someone as an assignee or a reviewer. Is that intentional?

2020-10-14 23:15 UTC, ecommerceUXdesign commented
@tjgrist not by design, just never set up the app.

2020-10-14 23:22 UTC, ecommerceUXdesign requested changes
Need to run this through an accessibility test to ensure that there are no new issues. 

Please update the commit logs. There should be no commits that are not in the [conventional commit format](https://github.com/AlaskaAirlines/auro/blob/master/src/CONTRIBUTING.md#conventional-commits)

You can also opt to squash your commits as well.

2020-10-15 00:48 UTC, tjgrist commented
> Need to run this through an accessibility test to ensure that there are no new issues.
Is this something I can do, if so, how?

I squashed my commits, thanks.

2020-10-15 15:01 UTC, geoffrich commented
> 
> 
> > Need to run this through an accessibility test to ensure that there are no new issues.
> 
> Is this something I can do, if so, how?
> 
> I squashed my commits, thanks.

I'd take a look at the defined keyboard interactions for radio buttons and make sure they all behave the same way. I'd especially want to make sure that you cannot focus a disabled radio button in an enabled radio group with the keyboard.

The [WAI-ARIA Authoring practices](https://www.w3.org/TR/wai-aria-practices-1.1/#radiobutton) are a good resource when you want to know how a component should behave. 

> - Tab and Shift + Tab: Move focus into and out of the radio group. When focus moves into a radio group :
>   - If a radio button is checked, focus is set on the checked button.
>   - If none of the radio buttons are checked, focus is set on the first radio button in the group.
> - Space: checks the focused radio button if it is not already checked.
> - Right Arrow and Down Arrow: move focus to the next radio button in the group, uncheck the previously focused button, and check the newly focused button. If focus is on the last button, focus moves to the first button.
> - Left Arrow and Up Arrow: move focus to the previous radio button in the group, uncheck the previously focused button, and check the newly focused button. If focus is on the first button, focus moves to the last button.

As long as those all behave as expected, we should be good. Let me know if you have any issues validating and I'd be happy to pair on it.

2020-10-15 20:25 UTC, blackfalcon requested changes
There are two issues. One that seems that was already an issue and another that was introduced. 

## Existing issue

It seems that there was already a bug where a selected node within a disabled group still has the tab-index of `0` meaning that even if the group disabled, a tab will land on the node that is marked as `checked`. 

Expectation: if the group is disabled, no tab should land on the group. 

## New issue 

With the new feature to disable individual nodes within a group, the tab order is not updated. To repro ...

1. Tab to the group
1. Use arrow keys to move up/down in the group

What happens is there is a phantom keydown when landing on a disabled node with no visual or audio response.

2020-10-17 05:10 UTC, blackfalcon commented
The issue of tabbing between the active nodes has been addressed, but when you first tab into the group it still selects the 1st node, even if it is disabled. 
<img width="548" alt="Screen Shot 2020-10-16 at 10 07 59 PM" src="https://user-images.githubusercontent.com/181089/96328869-5a887680-0ffc-11eb-9e71-c4516c9942c6.png">

2020-10-17 16:29 UTC, tjgrist commented
Created a new issue for the tabbing into group bug. I took a shot at fixing it but was having trouble.

2020-10-19 21:08 UTC, tjgrist commented
This PR now also addresses issue #7

2020-10-19 22:53 UTC, blackfalcon approved these changes

2020-10-19 22:54 UTC, ecommerceUXdesign approved these changes

2020-10-19 22:54 UTC, merged

2020-10-19 22:56 UTC, ecommerceUXdesign commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alaskaairux/auro-radio/v/1.1.0)
- [GitHub release](https://github.com/AlaskaAirlines/auro-radio/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: